### ISSUE TITLE
Installing qbehaviour_studentquiz makes it impossible to create any acitivity (in old themes)

### ISSUE THREAD

**Issue by timhunt** [frankkoch/moodle-qbehaviour_studentquiz#6]
This style rule causes problems:

https://github.com/frankkoch/moodle-qbehaviour_studentquiz/blob/master/styles.css#L44

```css
div.none, .hidden {
    display: none;
}
```

In a Moodle plugin, all CSS selectors used should include the plugin name. It is dangerous to change the styling of generic selectors.

For example, in old Moodle themes, the submit button for any form is in a <fieldset class="hidden">. Therefore, after installing studentquiz, You cannot submit any form. Therefore, you cannot create a studentquiz on your test server, to see how awesome it is!

Most of the CSS here, and in mod_studentquiz look fine. There are just a few rules (not just the one example above) that could usefully be fixed up. Thanks.

**Comment by mudrd8mz** [comment]
Thanks Tim for catching and reporting this. Reference for the maintainer: https://docs.moodle.org/dev/Plugin_contribution_checklist#CSS_styles

**Comment by eXpl0it3r** [comment]
This styling was introduced with the very first commit. Since I couldn't find where it really gets applied in our code and removing it didn't reveal any negative side effects in my tests, I've simply removed the style rule. If it does cause issues, it can be looked at it again but at least then we'd have a test case to look at.

Fixed in c5a4a860f5d4611c1b8c7730b9fb14457b0c4277

**Comment by timhunt** [comment]
Thanks!
